name: pciutils

on: push

jobs:
  build:
    name: pciutils
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build tools
        run: |-
          sudo apt-get update && sudo apt-get install -y nasm iasl build-essential uuid-dev python3 python3-pip git
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
          pip install ipug --user --upgrade --no-warn-script-location

      - name: Setup environment
        env:
          GIT_CONFIG_PARAMETERS: "'advice.detachedHead=false'"
        run: |-
          python project.py setup

      - name: Build
        run: |-
          python project.py

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: Build/**/X64/*.efi
